Updated syntax and added unbound

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,12 +1,20 @@
 #!/bin/bash
 
 function disableStubResolver(){
-    sed -r -i.orig 's/#?DNSStubListener=yes/DNSStubListener=no/g' /etc/systemd/resolved.conf
-    sh -c 'rm /etc/resolv.conf && ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf'
+    sed --regexp-extended 's/#?DNSStubListener=yes/DNSStubListener=no/g' \
+        --in-place=.bak /etc/systemd/resolved.conf
+    sh -c 'rm /etc/resolv.conf \
+        && ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf'
     systemctl restart systemd-resolved
 }
 
 function setupDocker() {
+
+    local i
+    local IP
+    local piholePass
+    local dockerStatus
+
     # Note: FTLCONF_LOCAL_IPV4 should be replaced with your external ip.
     docker run -d                                                    \
         --name pihole                                                \
@@ -25,21 +33,25 @@ function setupDocker() {
         pihole/pihole:latest
 
     printf 'Starting up pihole container '
+
+    dockerStatus="$(docker inspect -f "{{.State.Health.Status}}" pihole)"
     for i in $(seq 1 20); do
-        if [ "$(docker inspect -f "{{.State.Health.Status}}" pihole)" == "healthy" ] ; then
+        if [[ "${dockerStatus}" == "healthy" ]]; then
             printf ' OK'
-            echo -e "\n$(docker logs pihole 2> /dev/null | grep 'password:') for your pi-hole: http://${IP}/admin/"
+            piholePass="$(docker logs pihole 2> /dev/null | grep 'password:')"
+            echo -e "\n${piholePass} for your pi-hole: http://${IP:-..}/admin/"
             return 0
         else
             sleep 3
             printf '.'
         fi
 
-        if [ "${i}" -eq 20 ] ; then
-            echo -e "\nTimed out waiting for Pi-hole start, consult your container logs for more info (\`docker logs pihole\`)" >&2
+        if [[ "${i}" -eq 20 ]]; then
+            echo -e "\nTimed out waiting for Pi-hole start, consult your" >&2
+            echo -e "container logs for more info (\`docker logs pihole\`)" >&2
             exit 1
         fi
-    done;
+    done
 }
 
 function enablePiHoleService() {
@@ -47,11 +59,69 @@ function enablePiHoleService() {
     if [[ ! -f "${systemd_file}" ]]; then
         printf 'Adding Systemd init script..\n'
         touch systemd_file
-        echo -e "[Unit]\nDescription=pihole\nRequires=docker.service multi-user.target\nAfter=docker.service network-online.target dhcpd.service\n\n[Service]\nRestart=always\nExecStart=/usr/bin/docker start -a pihole\nExecStop=/usr/bin/docker stop -t 2 pihole\n\n[Install]\nWantedBy=multi-user.target" \
-            | tee "${systemd_file}" > /dev/null
+        {
+            printf "[Unit]\n"
+            printf "Description=pihole\n"
+            printf "Requires=docker.service multi-user.target\n"
+            printf "After=docker.service network-online.target dhcpd.service\n"
+            printf "\n"
+            printf "[Service]\n"
+            printf "Restart=always\n"
+            printf "ExecStart=/usr/bin/docker start -a pihole\n"
+            printf "ExecStop=/usr/bin/docker stop -t 2 pihole\n"
+            printf "\n"
+            printf "[Install]\n"
+            printf "WantedBy=multi-user.target"
+        } | tee "${systemd_file}" > /dev/null
+
         systemctl enable --now pihole.service
     fi
 }
+
+function setupUnbound() {
+    dnf install unbound --assumeyes
+
+    wget https://www.internic.net/domain/named.root -qO- \
+        | tee /var/lib/unbound/root.hints > /dev/null
+
+
+    {
+        printf "server:\n"
+        printf "    verbosity: 0\n"
+        printf "\n"
+        printf "    interface: 127.0.0.1\n"
+        printf "    port: 5335\n"
+        printf "    do-ip4: yes\n"
+        printf "    do-udp: yes\n"
+        printf "    do-tcp: yes\n"
+        printf "    do-ip6: yes\n"
+        printf "\n"
+        printf "    prefer-ip6: no\n"
+        printf "\n"
+        printf "    root-hints: \"/var/lib/unbound/root.hints\"\n"
+        printf "\n"
+        printf "    harden-glue: yes\n"
+        printf "\n"
+        printf "    harden-dnssec-stripped: yes\n"
+        printf "\n"
+        printf "    use-caps-for-id: no\n"
+        printf "\n"
+        printf "    edns-buffer-size: 1232\n"
+        printf "\n"
+        printf "    prefetch: yes\n"
+        printf "\n"
+        printf "    num-threads: 1\n"
+        printf "\n"
+        printf "    so-rcvbuf: 1m\n"
+        printf "\n"
+        printf "    private-address: 192.168.0.0/16\n"
+        printf "    private-address: 169.254.0.0/16\n"
+        printf "    private-address: 172.16.0.0/12\n"
+        printf "    private-address: 10.0.0.0/8\n"
+        printf "    private-address: fd00::/8\n"
+        printf "    private-address: fe80::/10\n"
+    } | tee /etc/unbound/unbound.conf.d/pi-hole.conf > /dev/null
+
 
 function main() {
     if ! command -v docker; then
@@ -64,9 +134,9 @@ function main() {
     fi
 
     PIHOLE_BASE="${PIHOLE_BASE:-$(pwd)}"
-    if [[ ! -d "$PIHOLE_BASE" ]]; then
-        mkdir -p "$PIHOLE_BASE" || {
-            echo "Couldn't create storage directory: $PIHOLE_BASE" >&2
+    if [[ ! -d "${PIHOLE_BASE}" ]]; then
+        mkdir -p "${PIHOLE_BASE}" || {
+            echo "Couldn't create storage directory: ${PIHOLE_BASE}" >&2
             exit 1
         }
     fi
